name: Build and Deploy to Instance

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      POSTGRES_URL: ${{ vars.POSTGRES_URL }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
      BASE_URL: ${{ vars.BASE_URL }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Tar for transit
        run: tar -czf ghost-in-the-tar.gz .next package.json pnpm-lock.yaml --ignore-failed-read

      - name: Upload build to droplet
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.INSTANCE_HOST }}
          username: ${{ secrets.INSTANCE_USER }}
          key: ${{ secrets.INSTANCE_SSH_KEY }}
          source: "ghost-in-the-tar.gz"
          target: "/root/logicstream"
          tar: false
          tar_tmp_path: ""
          strip_components: 0
          debug: true

      - name: Remote extract and start
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.INSTANCE_HOST }}
          username: ${{ secrets.INSTANCE_USER }}
          key: ${{ secrets.INSTANCE_SSH_KEY }}
          script: |
            cd /root/logicstream
            tar -xzf ghost-in-the-tar.gz
            /root/.nvm/versions/node/v22.18.0/bin/pnpm install --frozen-lockfile
            /root/.nvm/versions/node/v22.18.0/bin/pm2 restart logicstream || \
              /root/.nvm/versions/node/v22.18.0/bin/pm2 start /root/.nvm/versions/node/v22.18.0/bin/pnpm --name logicstream -- start

