name: Build and Deploy to Instance

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      POSTGRES_URL: ${{ variable.POSTGRES_URL }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
      BASE_URL: ${{ variables.BASE_URL }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Archive build output
        run: tar -czf build.tar.gz .next public package.json pnpm-lock.yaml next.config.js

      - name: Copy build to instance
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.INSTANCE_HOST }}
          username: ${{ secrets.INSTANCE_USER }}
          key: ${{ secrets.INSTANCE_SSH_KEY }}
          source: "build.tar.gz"
          target: "~/logicstream"

      - name: Remote extract and start
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.INSTANCE_HOST }}
          username: ${{ secrets.INSTANCE_USER }}
          key: ${{ secrets.INSTANCE_SSH_KEY }}
          script: |
            cd ~/logicstream
            tar -xzf build.tar.gz
            pnpm install --frozen-lockfile
            pm2 restart logicstream || pm2 start pnpm --name logicstream -- start
